URL = "https://eos.com/crop-monitoring/"
URL2 = "https://crop-monitoring.eos.com/login/auth"
TEST_EMAIL_URL = "https://mail.google.com/mail/u/2/#inbox"
PATH = "/usr/lib/chromium-browser/chromedriver"
NAME = "Tommy"
SECOND_NAME = "Smither"
EMAIL = "alexeykhoklov2@gmail.com"
PASSWORD = "qwerty1234"